version: '3'
services:
  digdag:
    build: .
    ports:
      - "65432:65432"
    volumes:
      - .:/digdag
    command: bash -c "digdag server -c server.properties -P params.yml"
    depends_on:
      - db
  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=digdag
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=digdag
  storage:
    image: minio/minio:RELEASE.2020-10-03T02-19-42Z
    environment:
      MINIO_ACCESS_KEY: digdag
      MINIO_SECRET_KEY: password
    ports:
      - "9000:9000"
    volumes:
      - ./.volumes:/storage
    entrypoint: sh
    command: -c "/usr/bin/minio server /storage"